import type { Metadata } from "next";
import { Logo } from "@/components/Logo";
import { VisageIcon } from "@/components/VisageIcon";
import "./globals.css";

export const metadata: Metadata = {
  title: "Visage — Professional AI Headshots",
  description: "Professional headshots, generated by AI, trained on you.",
  keywords: ["headshot", "AI", "portrait", "professional", "LinkedIn", "business"],
  authors: [{ name: "Visage" }],
  openGraph: {
    title: "Visage — Professional AI Headshots",
    description: "Professional headshots, generated by AI, trained on you.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="flex flex-col min-h-screen">
          {/* Header */}
          <header className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-xl">
            <div className="container mx-auto px-6 py-4">
              <nav className="flex items-center justify-between">
                <a href="/" className="group">
                  <Logo 
                    variant="lockup" 
                    size="sm" 
                    className="group-hover:opacity-80 transition-opacity"
                    iconClassName="text-accent group-hover:text-accent-muted transition-colors"
                  />
                </a>
                
                <div className="flex items-center gap-4">
                  <a href="/packs" className="btn-ghost">
                    My Packs
                  </a>
                  <a href="/packs/new" className="btn-primary">
                    New Headshot
                  </a>
                </div>
              </nav>
            </div>
          </header>

          {/* Main content */}
          <main className="flex-1">
            {children}
          </main>

          {/* Footer */}
          <footer className="border-t border-border py-8">
            <div className="container mx-auto px-6">
              <div className="flex flex-col md:flex-row items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <VisageIcon size={24} className="text-foreground-tertiary" />
                  <span className="text-foreground-tertiary text-sm">
                    Self-hosted AI Headshot Generator
                  </span>
                </div>
                <p className="text-foreground-tertiary text-sm">
                  Running on ElderTree
                </p>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
